#---
# tasks file for Sonarqube
---
- name: Install Java
  yum:
    name: "{{ java_package }}"
    state: present
  become: true

- name: Create sonar group
  group:
    name: "{{ sonar_group }}"
    state: present

- name: Create sonar user
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    shell: /bin/bash
    create_home: yes

- name: Download SonarQube
  get_url:
    url: "{{ sonar_download_url }}"
    dest: /tmp/sonarqube.zip

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt/
    remote_src: yes

- name: Rename SonarQube directory
  command: mv /opt/sonarqube-{{ sonar_version }} {{ sonar_install_dir }}
  args:
    creates: "{{ sonar_install_dir }}"

- name: Set ownership
  file:
    path: "{{ sonar_install_dir }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    recurse: yes

- name: Deploy systemd service
  template:
    src: sonar.service.j2
    dest: /etc/systemd/system/sonar.service
  notify: restart sonar

- name: Enable and start SonarQube
  systemd:
    name: sonar
    enabled: true
    state: started


